# Generated by Django 4.2.10 on 2024-08-22 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorelist',
            old_name='score',
            new_name='Nilai Bahasa Indonesia',
        ),
        migrations.RemoveField(
            model_name='scorelist',
            name='name',
        ),
        migrations.AddField(
            model_name='scorelist',
            name='Nilai Bahasa Inggris',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='scorelist',
            name='Nilai IPA',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='scorelist',
            name='Nilai Matematika',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
