# Generated by Django 4.2.10 on 2024-08-22 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_score_scorelist_nilai_bahasa_indonesia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorelist',
            name='Nilai Bahasa Indonesia',
        ),
        migrations.RemoveField(
            model_name='scorelist',
            name='Nilai Bahasa Inggris',
        ),
        migrations.RemoveField(
            model_name='scorelist',
            name='Nilai IPA',
        ),
        migrations.RemoveField(
            model_name='scorelist',
            name='Nilai Matematika',
        ),
        migrations.AddField(
            model_name='scorelist',
            name='bind_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Nilai Bahasa Indonesia'),
        ),
        migrations.AddField(
            model_name='scorelist',
            name='bing_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Nilai Bahasa Inggris'),
        ),
        migrations.AddField(
            model_name='scorelist',
            name='ipa_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Nilai IPA'),
        ),
        migrations.AddField(
            model_name='scorelist',
            name='mtk_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Nilai Matematika'),
        ),
    ]
