# Generated by Django 4.2.10 on 2024-08-24 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_registrationphase_alter_scorelist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='Tanggal Lahir : ')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Tempat Lahir : ')),
                ('gender', models.CharField(choices=[('p', 'Pria'), ('w', 'Wanita')], max_length=2, verbose_name='Jenis Kelamin : ')),
                ('religion', models.CharField(choices=[('i', 'Islam'), ('kk', 'Kristen Katolik'), ('pp', 'Kristen Protestan'), ('b', 'Buddha'), ('k', 'Konghucu')], max_length=2, verbose_name='Agama : ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', related_query_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
