# Generated by Django 4.2.10 on 2024-08-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='unique_code',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
