# Generated by Django 4.2.15 on 2024-09-03 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_faculty_prodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Alamat Domisil ')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registrationphase')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prodi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
